### ISSUE TITLE
[Question] Breakline for "Release body" field?

### ISSUE THREAD

**Issue by gigaga** [bitrise-steplib/steps-github-release#10]
Hi,

It's possible to use breakline for "Release body" field? I tried to use  "1\n2" but it doesn't work.
Also, possible to use Markdown format?

Best regards

**Comment by godrei** [comment]
Hi @gigaga ,
Both is possible, i just performed a quick test.
The body i provided for the step: `new draft\ntest**help**`
and it produced the following release: https://github.com/bitrise-samples/steps-github-release-test/releases/tag/untagged-68f121d977bb81afc94d

**Comment by gigaga** [comment]
Hi,

Your link is dead. Can you tell me if that can be work when release body is filled from an env var? 

Best regards
