### ISSUE TITLE
Add override support

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-github-release#5]
> Failed to create release: POST https://api.github.com/repos/[REDACTED]/[REDACTED]/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]

When releasing using a snapshot tag, the idea is to always have an up to date release. Not one release per commit. An override toggle would delete the current release before making a new one.

hub supports deleting in the release command:

- https://github.com/github/hub/blob/master/commands/release.go

This is my current work around:

```bash
#!/usr/bin/env bash

set -e

# Authorize hub
mkdir -p ~/.config/

cat << EOF > ~/.config/hub
github.com:
- user: bootstraponline
  oauth_token: $GH_TOKEN
  protocol: https
EOF

set +e

# errors if release doesn't exist
hub release delete "$SNAPSHOT_TAG"

exit 0
```

**Comment by bootstraponline** [comment]
The tag also has to be deleted. This can be done via the API:

```
#!/usr/bin/env bash

curl -u bootstraponline:$GH_TOKEN -X "DELETE" https://api.github.com/repos/TestArmada/flank/git/refs/tags/flank_snapshot

exit 0
```

**Comment by godrei** [comment]
@bootstraponline thanks for the feature request, we scheduled to implement this!

**Comment by bootstraponline** [comment]
Cool. If you have any questions, ping me on slack.
