### ISSUE TITLE
Resource:Release Field:target_commitish Code:invalid Message

### ISSUE THREAD

**Issue by gigaga** [bitrise-steplib/steps-github-release#9]
Hi support,

I am not able to publish m release to Github. I have the following error message
`Failed to create release: POST https://api.github.com/repos/.../releases: 422 Validation Failed [{Resource:Release Field:target_commitish Code:invalid Message:}`

Complete logs:

> +------------------------------------------------------------------------------+
> | (7) Github Release - only if PUBLIC_master branch                            |
> +------------------------------------------------------------------------------+
> | id: github-release                                                           |
> | version: 0.9.4                                                               |
> | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
> | toolkit: go                                                                  |
> | time: 2018-11-09T10:29:20Z                                                   |
> +------------------------------------------------------------------------------+
> |                                                                              |
> [34;1mConfig:[0m
> - APIToken: *****
> - Username: *****
> - RepositoryURL: git@github.com:....git
> - Tag: 0.0.2
> - Commit: 0.0.2
> - Name: Release v0.0.2
> - Body: 1\n2
> - Draft: yes
> - FilesToUpload: /bitrise/deploy/sdk-pvf-debug-androidTest.apk
> [31;1mFailed to create release: POST https://api.github.com/repos/...-> payment/releases: 422 Validation Failed [{Resource:Release Field:target_commitish Code:invalid Message:}]
> [0m

Can you tell me, what is the problem?

Best regards,

**Comment by bitce** [comment]
Hi @gigaga can you please send us a build URL as well?

**Comment by gigaga** [comment]
Hi @bitce 
Sure: https://app.bitrise.io/build/9335bd4cc05160c8

**Comment by gigaga** [comment]
I don't know why, but it's ok for now!

**Comment by gigaga** [comment]
@mackoj I think I had this issue because I referenced as commit a tag. I changed by master and after that it was ok

**Comment by mackoj** [comment]
I tried again this morning @bitce and it seems to work...
So ... I don't know
